name: AbCVista
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - libgcc=7.2
  - setuptools=59.5.0
  - pip
  - mkl=2024.0
  - openmm=7.7
  - pdbfixer
  - biopython==1.79
  - numpy==1.21
  - PyYAML==5.4.1
  - requests
  - scipy==1.7.1
  - tqdm==4.62.2
  - typing-extensions==3.10
  - wandb==0.12.21
  - modelcif==0.7
  - ml-collections
  - aria2
  - git
  - bioconda::hmmer==3.3.2
  - bioconda::hhsuite==3.3.0
  - bioconda::kalign2==2.04
  - pip:
      - torch==2.3.1
      - pytorch-lightning==2.3.3
      - peft==0.14.0
      - svgpath2mpl==1.0.0
      - deepspeed==0.12.4
      - dm-tree==0.1.6
      - pandas==1.3.5
      - qc-procrustes==1.0.0
      - jax==0.4.3
      - https://storage.googleapis.com/jax-releases/nocuda/jaxlib-0.4.3-cp39-cp39-manylinux2014_x86_64.whl
      - scikit-learn==1.5.2
      - kneed==0.8.5
      - antiberty==0.1.3
      - git+https://github.com/NVIDIA/dllogger.git
